
import com.sun.security.auth.NTSidPrimaryGroupPrincipal;
import java.awt.Image;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 * Formulario de registro de datos
 *
 * @author Euris Alc.
 */
public class Registro_Persona extends javax.swing.JFrame {

    /**
     * Creates new form Registro_Persona
     */
    public Registro_Persona() {
        initComponents();

        try {
            // Icono de los botones
            Image agregar = ImageIO.read(getClass().getResource("imagenes/icono_agregar.png"));
            Image limpiar = ImageIO.read(getClass().getResource("imagenes/icono_limpiar.png"));
            bInsertar.setIcon(new ImageIcon(agregar));
            bLimpiar.setIcon(new ImageIcon(limpiar));
        } catch (IOException ex) {
            Logger.getLogger(Registro_Persona.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tApellidos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tDireccion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tTelefono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbEstudios = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        bInsertar = new javax.swing.JButton();
        bLimpiar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDatos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro");

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de las personas"));
        jPanel4.setLayout(new java.awt.GridLayout(6, 2, 6, 2));

        jLabel1.setText("Nombre:");
        jPanel4.add(jLabel1);
        jPanel4.add(tNombre);

        jLabel2.setText("Apellidos:");
        jPanel4.add(jLabel2);

        tApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tApellidosActionPerformed(evt);
            }
        });
        jPanel4.add(tApellidos);

        jLabel3.setText("Dirección:");
        jPanel4.add(jLabel3);
        jPanel4.add(tDireccion);

        jLabel4.setText("Teléfono:");
        jPanel4.add(jLabel4);
        jPanel4.add(tTelefono);

        jLabel5.setText("Email:");
        jPanel4.add(jLabel5);
        jPanel4.add(tEmail);

        jLabel6.setText("Estudios:");
        jPanel4.add(jLabel6);

        cbEstudios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Primaria", "ESO", "Bachiller", "Grado medio", "Grado superior", "Grado universitario" }));
        cbEstudios.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbEstudiosItemStateChanged(evt);
            }
        });
        cbEstudios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEstudiosActionPerformed(evt);
            }
        });
        jPanel4.add(cbEstudios);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bInsertar.setText("Insertar");
        bInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInsertarActionPerformed(evt);
            }
        });
        jPanel3.add(bInsertar);

        bLimpiar.setText("Limpiar");
        bLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimpiarActionPerformed(evt);
            }
        });
        jPanel3.add(bLimpiar);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tbDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellidos", "Dirección", "Teléfono", "Email", "Estudios"
            }
        ));
        jScrollPane1.setViewportView(tbDatos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbEstudiosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbEstudiosItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEstudiosItemStateChanged

    private void tApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tApellidosActionPerformed

    private void bInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInsertarActionPerformed
       // Obtenemos el modelo de la tabla
        DefaultTableModel modelo = (DefaultTableModel) tbDatos.getModel();

        // Agregar los valores
       Object[] fila = new Object[6];
       
       fila[0] = tNombre.getText();
       fila[1] = tApellidos.getText();
       fila[2] = tDireccion.getText();
       fila[3] = tTelefono.getText();
       fila[4] = tEmail.getText();
       fila[5] = cbEstudios.getSelectedItem().toString();

        // Llamar método
        modelo.addRow(fila);
        
        tbDatos.setModel(modelo);
    }//GEN-LAST:event_bInsertarActionPerformed

    private void cbEstudiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEstudiosActionPerformed
        // TODO add your handling code here:
        
        String item_seleccionado = cbEstudios.getSelectedItem().toString();
    }//GEN-LAST:event_cbEstudiosActionPerformed

    private void bLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimpiarActionPerformed
        // Obtenemos la fila seleccionada de la tabla
        int fila = tbDatos.getSelectedRow();

        // Obtenemos el modelo de la tabla
        DefaultTableModel modelo = (DefaultTableModel) tbDatos.getModel();

        if (fila < 0) {
            // En caso de no seleccionar una fila
            JOptionPane.showMessageDialog(null,
                    "Debe seleccionar una fila de la tabla");
        } else {
            int confirmar = JOptionPane.showConfirmDialog(null,
                    "Seguro que desea Eliminar el registro? ");
            
            if (JOptionPane.OK_OPTION == confirmar) {
                   
                // Eliminamos el modelo de la tabla
                modelo.removeRow(fila);
                JOptionPane.showMessageDialog(null,
                        "Registro Eliminado");
            }
        }
    }//GEN-LAST:event_bLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_Persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_Persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_Persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_Persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_Persona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bInsertar;
    private javax.swing.JButton bLimpiar;
    private javax.swing.JComboBox<String> cbEstudios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tApellidos;
    private javax.swing.JTextField tDireccion;
    private javax.swing.JTextField tEmail;
    private javax.swing.JTextField tNombre;
    private javax.swing.JTextField tTelefono;
    private javax.swing.JTable tbDatos;
    // End of variables declaration//GEN-END:variables
}
